version: '2'

services:
   ora2pg-client:
      build:
         context: ./ora2pg-client
      image: cismet/ora2pg-client:1.0-SNAPSHOT
      environment:
         - DB_HOST=${DB_HOST}
         - DB_SID=${DB_SID}
         - ORA2PG_USER=${ORA2PG_USER}
         - ORA2PG_PASSWD=${ORA2PG_PASSWD}
      container_name: ora2pg-client
      volumes:
         - ./export:/export
